controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    extra_joints: ["right_wheel_joint", "left_wheel_joint"]

tricycle_controller:
  ros__parameters:
    type: tricycle_steering_controller/TricycleSteeringController

    # Model
    traction_joints_names: ["traction_joint"] # Name of traction joint in URDF
    steering_joints_names: ["steering_joint"] # Name of steering joint in URDF
    traction_wheels_radius: 0.3 # Radius of front wheel
    wheelbase: 1.7 # Distance between center of back wheels and front wheel

    # Odometry
    odom_frame_id: odom
    base_frame_id: base_link
    open_loop: false # if True, uses cmd_vel instead of hardware interface feedback to compute odometry
    enable_odom_tf: true # If True, publishes odom<-base_link TF
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Need to be set if fusing odom with other localization source
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Need to be set if fusing odom with other localization source
    velocity_rolling_window_size: 10 # Rolling window size of rcppmath::RollingMeanAccumulator applied on linear and angular speeds published on odom

    reduce_wheel_speed_until_steering_reached: true # If true, limits wheel speed when steering angle is far from reference to avoid slipping.

    # cmd_vel input
    reference_timeout: 0.5 # In seconds. Timeout to stop if no cmd_vel is received
